### ISSUE TITLE
Config file for codename "anglee"?

### ISSUE THREAD

**Issue by tsantor** [spocky/miproja1#1]
Do you have a config file for codename Anglee (Model MJJGYY02FM)?

Also, when trying to Change Source to HDMI 1 via your tools I get:
```This app could not be found. Please make sure com.xiaomi.mitv.tvplayer is installed.```

Also, when trying to go to Projector Settings I get:
```This app could not be found. Please make sure com.xiaomi.mitv.settings is installed.```

Any ideas?  I can't find those packages anywhere to install on the projector.

**Comment by spocky** [comment]
Sorry for not responding publicly before.
These tools are currently dedicated to MiTv devices (Xiaomi chinese UI, using android 6.0.1).
Anglee is an international model, shipping with android 8.1. Unfortunately most features (such as setting input source) won't be applicable on it.
If I can get my hands on an international model, I'll do my best to add support for it.

**Comment by tsantor** [comment]
No Problem.  As mentioned via email, we got around the issue by simply using `adb` commands over Wi-Fi to select HDMI input on Android 8.1.  We automate the process so when our app starts it tells the projector to change its input to HDMI 1 as each time the projector is rebooted it doesn't "remember" you were using HDMI 1 or whatever input you selected.

**Comment by jdknox** [comment]
@tsantor, could you post how you were able to connect using `adb` over Wi-Fi?

**Comment by jdknox** [comment]
@tsantor Which `adb` commands do you send to change the HDMI input?

**Comment by tsantor** [comment]
@jdknox - unfortunately I was never able to get it to change HDMI input by issuing a single ADB command, which would have been preferable.   As mentioned I ended up simply sending `adb shell input keyevent`'s over ADB to "navigate" to HDMI 1. Essentially mimicking a person using the remote.  Worked every time.

**Comment by spocky** [comment]
@tsantor Recent versions of my tools can change HDMI input on international models (upcoming release will also be available on Google Play). As they also support automatic change to a selected HDMI on boot, this may replace your adb script if you ever need to.

**Comment by wawachi** [comment]
Hello @spocky , I actually use the same "adb" hack than @tsantor , but it's not really futureproof. 
I've installed your last version of ProjectIvy (3.56), however the automatic input change don't work. Is it because I need to update my anglee projectors ? Did I need to root ?
