### ISSUE TITLE
Stuttering isssue 

### ISSUE THREAD

**Issue by x7p7p** [spocky/miproja1#103]
Downloaded new update from google playstore before it was silky smooth after update its stuttering when navigating through the home screen i got google Chromecast how do i fix this ?

**Comment by x7p7p** [comment]
After using for a while it got better 👍

**Comment by kindall** [comment]
I found that enabling "Load cards while scrolling" (in the Appearance category of the Projectivy settings) smoothed this out, although the description implies the opposite.

**Comment by spocky** [comment]
@x7p7p thanks for letting me know it improved over time !

@kindall 
"Load cards while scrolling" will load cards resources (thumbnails) during the scrolling animation. You will get the pictures faster but this will negatively impact the fps during scrolling as the CPU will have more work to do. 
On the other hand, with this feature not enabled, the thumbnails will only be loaded when there is no scrolling occurring : this will delay the cards loading, but scrolling animation will be smoother as the CPU will be focused on animating rows.
