### ISSUE TITLE
Feature Request: Add Any Movie/Show to a Category

### ISSUE THREAD

**Issue by grumpyshorts** [spocky/miproja1#105]
Today, users can select content from a channel (e.g., Disney+ or Hulu) and then add or move it to a category. Users can use this ability to create a watchlist or favorites list. However, users can only select content presented in an existing channel, which is limited to about 10-50 movies/shows per channel. Users don't have a way to add a favorite that isn't in an existing channel. For instance, Shogun may not show as a Hulu recommendation even if the user is actively watching the show. Please provide a way to add content that isn't in an existing channel.

**Comment by spocky** [comment]
Sorry, this is not possible. There is no way for an app to get all the shows available in an app.
It works the opposite way : apps fill in a shared database with any program they want, in any number of channel they want. Projectivy requests this database to show channels and programs. 
Anything that is not in this database can't appear in Projectivy.
