### ISSUE TITLE
Bug with Amlogic device

### ISSUE THREAD

**Issue by ili3973** [spocky/miproja1#108]
I have a problem with my H96MAX with Android 11 and Amlogic processor. When I use the launcher, I can open and use the first line of apps. But if I press the up or down button, the launcher restart.

**Comment by spocky** [comment]
Does this happen immediately after the onboarding screen or did you change any setting before it started behaving this way ?

**Comment by ili3973** [comment]
Thanks, but it's not necessary. I uninstalled and reinstalled and used an old backup. The problem happened to me when I used TV Quick Actions to create a channel with some apps with different icons, and then move the apps to their respective categories. Then the app started crashing for me. I would like to suggest an integrated way to change the icons from the launcher itself. Anyway, thank you very much, and I have activated the bug report.
