### ISSUE TITLE
Nvidia Shield TV remote volume no longer works

### ISSUE THREAD

**Issue by No-Dot7369** [spocky/miproja1#117]
With the latest update, I noticed the volume on my shield remote control no longer shows on screen or works for that matter

**Comment by spocky** [comment]
I don't think this is related to Projectivy's as it does not interact with volume in any way. And I'm using my shield every day and never noticed this kind of problem. 
May I ask you to reboot your shield and verify its parameters ?

**Comment by No-Dot7369** [comment]
I rebooted my shield and after going into settings I realized that a
soundbar was still listed that I stopped using a while ago.  I unclicked on
soundbar and now shield volume control shows on screen. I apologize for
wasting your time on this matter. I also want to thank you for making the
best Android TV Launcher available
