### ISSUE TITLE
Enhancement: Tile Gap Alignment 

### ISSUE THREAD

**Issue by Nuvibez** [spocky/miproja1#122]
Right now the the gap between tiles changes when changing tile size. Example: the larger the tile, the bigger the gap between tiles. It makes the tiles look unorganized when there are rows with different tile sizes because the gaps between tiles don't match/align. Can you please make the gap between tiles "equally fixed/align" no matter the size of the tile like on the native android tv launcher, it would make for a better organized screen. Also can you make the tiles symmetrically line up. E.g. 
2 extra small tiles on one row, line up with 1 large tile in the row above/below like the native android tv launcher. I think that might get automatically fixed with the "fixed gap alignment". Thank you.

**Comment by spocky** [comment]
Fixed in next release
