### ISSUE TITLE
"Now Playing" category has never worked

### ISSUE THREAD

**Issue by jiznon** [spocky/miproja1#139]
Running latest v4.54. I absolutely love this launcher, it's prevented me from throwing my Shield TV and Bravia TV out a window due to all the invasive ads.

That said, I miss seeing what is currently playing on YouTube or Spotify. I see that Projectivy has a "Now Playing" category, however I've never seen it work. In Settings, it has a circle with a line through it behind an eyeball symbol (different from the eyeball symbol with a line through it without a circle) -- what does this mean? "Visible" is toggled on, yet I've never seen this work.

Any help would be greatly appreciated!

*EDIT: Of course once i posted this i find the solution (after searching on and off for months):

Settings -> Apps -> Special App Access -> Notification Access

Found here: https://www.reddit.com/r/AndroidTV/comments/18yigpd/spotify_now_playing_on_projectivy_launcher/kgib6ks/

Love this launcher!

**Comment by Arcitec** [comment]
Thanks for documenting the solution. :) I was curious about this feature too, and thanks to you I can see that I had already given it notification access (Projectivy asks for that during first launch).
