### ISSUE TITLE
Prime Video channel tiles are blank

### ISSUE THREAD

**Issue by Kr1ptiq** [spocky/miproja1#14]
Running this on a Shield TV Pro 2019. Fully updated.

As the title states, the Prime Video channel on the home screen is showing blank tiles. 

This issue was reported on XDA re version 4.24 and this 4.30 release suggested a fix, however I am still having this issue.

**Comment by jhedfors** [comment]
This is fixed for me in v4.31.

**Comment by Kr1ptiq** [comment]
Yes it's fixed on 4.31, thanks
