### ISSUE TITLE
ProjectIvy refusing to stick as default launcher after latest updates on Nvidia Shield Pro 2017

### ISSUE THREAD

**Issue by drout69** [spocky/miproja1#143]
After updating all apps on my Nvidia Shield, which I belive included some of the lower level Google TV Home type apps,  ProjectIvy is no longer sticking as the default launcher.

It appears that the Accesabilty override is not working how it used to,  as ProjectIvy is now complaining about accessibility settings not being set,  when they are just the same as they were prior to the updates. 

Do you have a way to replicate this?

**Comment by spocky** [comment]
Hi,

My Nvidia shield 2019 doesn't show this behavior.
Android sometimes shows an accessibility service as enabled although it's not really. This happens after an app or system update.
Please try to disable Projectivy's accessibility service in Android settings, and enable it again. If started correctly, it should redirect you automatically to Projectivy home screen just after being enabled. It's usually sufficient to fix this issue.

**Comment by drout69** [comment]
I thought I had already tried that. Does it matter if there is a restart after disabling and enabling? To make those changes more "sticky". I don't have access to the device right now,  will try again and update when I can.

**Comment by Codling** [comment]
I have the same issue on my Shield TV Pro 2019 after updating apps few days ago.
Diable and enable the Accessibility service doesn't work.

Can you please fix it?

**Comment by drout69** [comment]
OK, I tried the unset, reboot, enable routine and it was still refusing to stick as accessibility enabled. 

I then checked the play store and saw there were updates available (again) for "Android TV Home", "Android TV Core Services", and "TV Setup", I installed those and rebooted, and Boom, the device restarts in ProjectIvy.

There has to have been a bug in the previously installed Google services.  For now,  resolved.

**Comment by drout69** [comment]
![20240725_225934](https://github.com/user-attachments/assets/d0a607fb-d230-437e-bcc7-19d6892f87df)
Those are the versions I updated to this morning.

**Comment by drout69** [comment]
Closing since the issue was resolved with another update for mentioned Google services.  Likely the issue was caused by bugs in the Google services.

**Comment by drout69** [comment]
Closing since the issue was resolved with another update for mentioned Google services.  Likely the issue was caused by bugs in the Google services.
