### ISSUE TITLE
GoogleTV updated today and broke launcher override 

### ISSUE THREAD

**Issue by SlicingKnife** [spocky/miproja1#155]
GoogleTV version 1.0.660160223 update stops Projectivity Launcher from auto launch.

**Comment by spocky** [comment]
I suppose you're using the accessibility service to override the stock launcher. 
Make sure it's still running (in Projectivy's "accessibility service" entry, you can see if it's currently running, don't trust what's in the stock settings accessibility menu, it might be enabled but not running. If it shows as enabled, try to disable it and then reenable it.
(I've just updated my ccwgtv to 1.0.66 and it seems to work as before).

**Comment by SlicingKnife** [comment]
I disabled and enabled each time before I restarted. 
Maybe I should uninstall reinstall Projectivy. 
I'll do that later and reply with results 

⁣Kindest regards
Stan Uptagrafft ​

**Comment by SlicingKnife** [comment]
I uninstalled and visited playstore on my pc and selected to install on another device and selected my HiSense TV. I watched it install. I launched it from the icon and in Settings, selected 'Manage settings' , 'Import' and selected a previously saved configuration, then returned my Home page went then to 'Android settings', 'Systen', 'Accessibility', 'Projectivity Launcher' and enabled that.
I then went to 'System', 'Restart'

Upon boot, it goes to the GoogleTV menu and when I press 'Home' on the remote, GoogleTV menu.


  

I must manually launch Projectivity to see my preferred Home screen.


  

You mention "Accessibility service", when I visit that menu pick, it shows 'Enabled: No'

below that I have checked 'Use alternative config' and 'Show reminder'


  

Please advise.


  
   Kindest regards,  
    Stan Uptagrafft  
    
    ***@***.*** 
    
  
  
  
  
  ------ Original Message ------
     Received: 11:49 AM EDT, 09/06/2024

**Comment by SlicingKnife** [comment]
Yep, that is likely the issue: Accessibility service is not enabled.
I have another HiSense TV that I did not upgrade it's GoogleTV and I checked 'Accessibility service' and it's ON.

I cannot see how to enable it... it's not a mouse option.

I suspect I'll need a tool or I may need to edit a file on the TV.
  
  I'm searching the web now to find out what is needed to enable it.
  
  Thanks for the tip.
    
    
     Kindest regards,  
      Stan Uptagrafft  
      
      ***@***.*** 
      
    
    
    
    
    ------ Original Message ------
       Received: 11:49 AM EDT, 09/06/2024

**Comment by SlicingKnife** [comment]
Yes, I see the Accessibility Service is not enabled as shown in Projectivity Launcher. When I visit Accessibility in Android I have selected Projectivity Laucher: ON.  Previously, this enabled Accessibility, after this GoogleTV that no longer works.
To clarify:
In Android Settings/System/Accessibility/Projectivy Laucher: ON
In Projectivity Launcher/Settings/Accessibility service/Enabled: NO  <-- this should display YES because of the line above.
I have uninstalled and reinstalled both this GoogleTV update and Projectivity Launcher without success.
Is there a service_config.xml, or similar file, I need to manually edit after this GoogleTV update?

**Comment by SlicingKnife** [comment]
FIXED.
I downloaded the apk file from APKPure into the TV's "DOWNLOAD" folder and launched it from there.  Instantly the Accessibility service is now Enabled.    \o/
It appears Projectivy does not install correctly from PlayStore.

**Comment by SlicingKnife** [comment]
Dang, I turned the TV on again and Accessibility service is OFF!  I stopped the process, cleared data, uninstalled and reinstalled from the previous download and Accessibility service remains OFF. It appears GoogleTV does not want another launcher. :/

**Comment by Thorfinn66** [comment]
Best option is to disable Google launcher (You need to disable 2 apps) Then set Projectivy Launcher as your default launcher.

**Comment by SlicingKnife** [comment]
That sounds good.  You mentioned I need to disable 2 apps, which are those?

**Comment by Thorfinn66** [comment]
> That sounds good. You mentioned I need to disable 2 apps, which are those?

Install ADB TV app (For TV) or atvTools app (for phone) Both gives you access to ADB shell (You can also use them to disable/uninstall apps)

Get current launcher (Save that value case you want to revert):
cmd shortcut get-default-launcher.

Set Projectivy Launcher as default:
cmd package set-home-activity com.spocky.projengmenu/com.spocky.projengmenu.ui.home.MainActivity

pm disable-user --user 0 com.google.android.tvlauncher
pm disable-user --user 0 com.google.android.tungsten.setupwraith

Make sure you set the new launcher before you disable the original Google TV launcher.
After this, you dont need to use Accesibility Mode for Projectivy Launcher.

**Comment by XBadFellaX** [comment]
I was going crazy over this, thought its just me, but after the September update launcher override has not been working. You go to settings to enable accessibility but as soon as you turn the tv off and turn it back on, accessibility is turned off. Not sure what changed after the update, it was working fine before the update.

**Comment by Thorfinn66** [comment]
I have similar problem with other apps, where accessibility settings won't stick.

I read here, that it could be because app listens for HOME button.

https://stackoverflow.com/questions/78622011/accessibility-service-in-android-tv-app-disabled-automatically-showing-enabled

If you set Projectivy Launcher as default launcher, you don't need accessibility turned on.

**Comment by SlicingKnife** [comment]
I just upgraded my 2nd HISENSE TV's built-in GoogleTV and once again Projectivy Launcher no longer controls the Home button.  I need to uninstall the recent GoogleTV.  Accesssibility is OFF once again, even though I have Accessibility Projectivy Launcher ON, it's shown as OFF.

**Comment by SlicingKnife** [comment]
Thanks for the replies [Thorfinn66](https://github.com/Thorfinn66) but your suggested fix is beyond my skillset.  I'll just use GoogleTV and hope a future release of Projectivy Launcher overcomes this latest GoogleTV issue.

**Comment by SlicingKnife** [comment]
FIXED - I unstalled the updates for GoogleTV and reinstall Projectivy Launcher. The HOME button now brings me to the Projectivy Launcher Home.  I am keeping the APK file in the TV's download folder so I can reinstall Projectivy Launcher again easily.
