### ISSUE TITLE
Show app Names / Channel Banner shows as settings wheel

### ISSUE THREAD

**Issue by Fabrice19730526** [spocky/miproja1#16]
For some apps e.g. FoxNow or France TV, the channel banner displays as the settings logo in the channel's recommendations' row.
It can obviously be hidden by disabling Show app names, but then you can't read the tile or synopsis.

**Comment by spocky** [comment]
Never experienced it myself (France Tv working fine here). Is it still a problem on the latest release ?

**Comment by Fabrice19730526** [comment]
The issue is still there on 4.35. See screenshot attached.
![Screenshot_20230725-072245](https://github.com/spocky/miproja1/assets/63492160/01e2ce15-380a-400e-82cd-ccbe31629686)

**Comment by spocky** [comment]
Fixed in next release (4.50?)
