### ISSUE TITLE
Reddit wallpaper issue

### ISSUE THREAD

**Issue by Kr1ptiq** [spocky/miproja1#18]
With all the controversy at Reddit regarding api pricing, and subs going dark, would it be possible to use our own custom RSS feeds to pull wallpaper? 

Or perhaps some non-reddit wallpaper options?

**Comment by spocky** [comment]
Well it's not that easy : RSS doesn't define standard fields, which means that current parser wouldn't know where to find url, resolution, author...
I'd like to explore the possibility of opening Projectivy to third party plugins for things such as wallpapers providers. I just didn't take time to do it yet.

**Comment by SuXlife** [comment]
Just installed and am wondering if the Reddit wallpapers are still working? Not a premium user (yet.) Are the Reddit wallpapers available on the free version? 

For some reason when I select any of them it only shows the default picture. Nvidia Shield Pro.

**Comment by BrokenAdmiral81** [comment]
> Just installed and am wondering if the Reddit wallpapers are still working? Not a premium user (yet.) Are the Reddit wallpapers available on the free version?
> 
> For some reason when I select any of them it only shows the default wallpaper. Nvidia Shield Pro.

Yes I have the same issue, wallpaper stuck on default wallpaper even if I do select a different option. Does not refresh at all. Any suggestions?

**Comment by BrokenAdmiral81** [comment]
> > Just installed and am wondering if the Reddit wallpapers are still working? Not a premium user (yet.) Are the Reddit wallpapers available on the free version?
> > For some reason when I select any of them it only shows the default wallpaper. Nvidia Shield Pro.
> 
> Yes I have the same issue, wallpaper stuck on default wallpaper even if I do select a different option. Does not refresh at all. Any suggestions?

So I am not sure how this was resolved, but my wallpapers are working as should. I changed the default launcher back to Android TV Home just to see how shit it was again. When launching Projectivy and setting it back to my default launcher, it was working. So not a real solution, but working.

**Comment by tstack77** [comment]
Possible to simply allow a user folder for backgrounds that cycle every x minutes? Also would be nice to have the clock/status bar adjust its color.

**Comment by spocky** [comment]
Closing this as there's no reddit wallpaper issue. More options will be available regarding wallpapers in the next release.
