### ISSUE TITLE
Status bar - Feature request

### ISSUE THREAD

**Issue by Kr1ptiq** [spocky/miproja1#19]
Could we have an option on the status bar to open the 'notifications' pane. On my shield tv pro this pane shows background now playing info (eg Spotify) as well as mounted drives and other notifications. 

Currently there is no way to get to it in ProjectIVY.   Would be even better if that icon only shows if there are notifications available.

**Comment by spocky** [comment]
4.35 addresses this request : a long press on the notification icon will open the stock notification panel if available. Note that you can also select "show notification icon when empty" in Projectivy settings to make sure the stock notification panel is always available.
