### ISSUE TITLE
How to add Mijia Lite/ Youth Edition to the list of codenames you have

### ISSUE THREAD

**Issue by Dhruv222** [spocky/miproja1#2]
I bought a new Projector from Xiaomi called Mijia Lite/Youth Edition, the app cant seem to get the file over the internet when it first loads which i assume is because it has a different codename. 

First Can you help me by telling me how can i find the codename and after that if there are any changes that i need to do to the json files? Can i just copy them and change the naming and other relevant and obvious bits.

I have a pmed you on XDA as well regarding this, i followed your article to the dot and even rooted to make sure i get the option.

Thank you so much for the work, you are doing and i would like to help out with that.

**Comment by spocky** [comment]
For the record, your device name can be found using the Miinfo app, from Loly [available here](https://mega.nz/#!i75XVQCS!HL7-aCoeI8kg4ocR_qsax7OrP-sA6gLJqB-871_C-Q0).
You can also just connect to your device using adb :
`adb connect ip_of_your_device`
`adb shell`
your prompt will be something like :
`shell@device_codename:/ $`
