### ISSUE TITLE
Shortcuts missing if hidden forever 

### ISSUE THREAD

**Issue by cowballz** [spocky/miproja1#20]
I found a bug. If you hide shortcuts from the menu it will disappear completely from the home screen as an option if you close or reboot the device. Only way to fix is to restore the launcher to factory via settings.

Adding a new shortcut won't make it appear again.

**Comment by spocky** [comment]
Thanks for the bug report 👍. "Now playing" also suffers from the same bug.
This will be fixed on the next release.
