### ISSUE TITLE
OVO K1 Projector unable to install "Conflict"

### ISSUE THREAD

**Issue by LunarstarPony** [spocky/miproja1#25]
Not sure if this is the right place for this or not but I've been having issue installing the Projectivy Launcher on my OVO K1 Projector.

It seems like this projector is using some sort of modified Projectivy Launcher by default which cause it when I try to install the APK File It would just show "The Package conflict with an existing package by the same name".

So I'm wondering is there anyway to get the Launcher to work on my devices?

**Comment by spocky** [comment]
This is a bit surprising. It probably means that your OVO K1 ships with a hacked version of Projectivy Launcher.
Would you mind sharing (privately if you prefer) where you bought it ?

Regarding your issue, it depends on how it got installed on your device :
- installed by the reseller : you can use adb to uninstall it and then install the real app
- directly embedded on the factory system image : it can't be uninstalled. Not sure if that will work, but you can have a look here for a workaround https://www.makeuseof.com/tag/run-multiple-app-copies-android/
