### ISSUE TITLE
Accessibility Settings turning off itself 

### ISSUE THREAD

**Issue by ashaykapadiya** [spocky/miproja1#26]
I have Mi TV 4i 55inch Tv and i was using 4.24 build up until now and it was working fine, on latest version sometimes my remote becomes unresponsive and have to use my mobile's ir blaster to operate the tv as accessibility in launcher settings shows off, however when i open tv settings it shows accessibility is ON. Then i have to turn it off and ON again to make my tv remote work.Any idea regarding this?
Only power button works, so when i shutdown the tv and turn it ON again then again accessibility option gets ON again in app

**Comment by spocky** [comment]
Accessibility state in Android settings doesn't reflect the current state but the theoretical state. So if the accessibility service decides to stop by itself (which isn't done by Projectivy) or if it crashes (which is obviously what I suspect), then it will appear as "ON" while not running anymore. Unfortunately, my logs haven't shown any crash in accessibility service for monthes, so I don't know where to search. If you could find how to reproduce it, that would be great.
What's your OS (MI Tv ?) and Android version ?

**Comment by ashaykapadiya** [comment]
Ok i am using stock os on my Mi 4i 55inch non rooted, to reproduce it, click on projectivy setting and click on appearance then go status and then  adjust time size after returning back to homescreen, popup to enable accessibility comes

**Comment by cowballz** [comment]
If you're using Android 9 and below it turns off all accessibility apps at random. It's a old bug with the system not the app.

**Comment by ashaykapadiya** [comment]
Oh, i was using 4.24 version till today but never faced that issue with that version ,so reported

**Comment by spocky** [comment]
> Ok i am using stock os on my Mi 4i 55inch non rooted Android 6.0.1 with mi's patchwall os, to reproduce it, click on projectivy setting and click on appearance then go status and then adjust time size after returning back to homescreen, popup to enable accessibility comes

I've been able to reproduce and fix it on Android 6. Thansk!
It was related to the way Projectivy restarts when some settings change (seems to kill the accessibility service on old Android version, not on recent ones). 
It will ship with next release.
