### ISSUE TITLE
unable to download googleplay/sevices package via app, unfreeze doesn't function.

### ISSUE THREAD

**Issue by gqbigpaps** [spocky/miproja1#29]
the source listed on the json file for the googleplay/services package seems unreachable which is the cause of the error when I try to download it through the launcher via 3rd party app menu.

also freezing recommended works fine at first but after that I cannot unfreeze, at least not automatically.
Freezing recommended took away the keyboard T.T

I am rooted on version 4.35 of the launcher and on rainman

**Comment by spocky** [comment]
Server address has just been updated, sorry it took that long.
Regarding the keyboard, you need to install the "Leanback keyboard" from "3rd party apps install".

**Comment by gqbigpaps** [comment]
Thanks bro!!
