### ISSUE TITLE
Google services not showing / Link doesn't work

### ISSUE THREAD

**Issue by demlasjr** [spocky/miproja1#31]
I'm trying to install Google Services on my Fengmi proyector, however, none of the app version shows the link. 
I manually find here the link to download the file (http://195.154.161.97/uploads/gapps.06d1a76b314a762d7db6884d7196f4e2.tar.gz) but the server is down. Can you please fix or share the file with me? Thank you.

Kind regards.

**Comment by viliiik** [comment]
I have same problem even after latest release 4.36. All the Aptiode links works for me but those one pointed to 195.154.161.97 not. Device: conan

**Comment by cobch** [comment]
I thought that we needed to root the device to make the google services work on the fengmi OS. Maybe I am wrong... I have the fengmi cinéma 4k pro

**Comment by demlasjr** [comment]
@viliiik I confirm that the developer confirmed on da-developers forum that in few days the issue will be fixed with the server. He is changing the server right now. All option will appear itself without having to update the app.

@cobch that's right, you have to root it first through Magisk

**Comment by cobch** [comment]
@demlasjr Great news but is it possible to root the fengmi cinéma pro 4k which is using Android 9?

**Comment by viliiik** [comment]
> @viliiik I confirm that the developer confirmed on da-developers forum that in few days the issue will be fixed with the server. He is changing the server right now. All option will appear itself without having to update the app.
> 
@demlasjr Thanks for the info, I saw the latest version 4.36 available so I thought this is already fix. I will wait until the server is up and running.

@cobch Of course I rooted the device first. There is a whole forum on how to do that here:
https://xdaforums.com/t/guide-recovery-rom-xiaomi-fengmi-wemax-mi-led-laser-projector-tv.3851755/

**Comment by cobch** [comment]
I was well aware of that forum but it says "only models using Android 6 can be rooted yet." Mine is running Android 9 that is why I asked you if something new happened (-:

**Comment by demlasjr** [comment]
@cobch you can try it, you have nothing to lose. Magisk will work or will fail....just give it a try. I don't think it will be an issue.

**Comment by spocky** [comment]
The package has been reuploaded and link updated. If it still doesn't work, there may be a caching issue, just reset app settings and start again.
