### ISSUE TITLE
[Request] Neon Glow Icon Highlight

### ISSUE THREAD

**Issue by icpryde** [spocky/miproja1#36]
I would love to have this glow that goes behind the icons which is on the standard google tv launcher I just find it's very nice and clean to look at, especially with a black background and the background will have a subtle colour change as well would be even more awesome.

![IMG_1016](https://github.com/spocky/miproja1/assets/29389746/6e25f7f1-7208-4e7f-b22b-a59adb987fc8)

Thank you for your hard work your launcher is awesome!

**Comment by spocky** [comment]
Although it won't be exactly the same, the next release will provide a glow effect. I hope you'll like it.

**Comment by icpryde** [comment]
> Although it won't be exactly the same, the next release will provide a glow effect. I hope you'll like it.

oh thats awesome i'm excited to try it out thank you!
