### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by rizreflects** [spocky/miproja1#37]
Hello there,

I have been using your launcher on a rooted Ugoos AM6B and am struggling to get the channels working. When the device boots up I get the following error message:

![20231111_173712.jpg](https://github.com/spocky/miproja1/assets/76912707/2cac2f7c-411e-423a-b89d-c349549a72dd)

It seems I have no option to enable channels either:

![20231111_173515.jpg](https://github.com/spocky/miproja1/assets/76912707/33704d99-4d5d-432e-9ddc-ce205b424792)

Is this feature only available on Nvidia Shield or am I doing something incorrectly? Any help will be appreciated.

**Comment by spocky** [comment]
Hi,

When you start Projectivy for the first time, it will ask for read_tv_listing permission if available on your device.

If your have this issue it's either one of these :
- you didn't allow this permission (in which case you can't still allow it manually in Android settings)
- your device doesn't support tv listings (I don't know Ugoos AM6b, does the stock launcher show channels ?)

**Comment by rizreflects** [comment]
I've reinstalled the app multiple times and never recieved the permission request. I'd have definitely allowed it. The stock launcher on the Ugoos doesn't support channels as far as I'm aware. The stock launcher looks more like something you'd see on a tablet. Is there anyway around this for me? I'd really love to see the channels but it's understandable if there's nothing you can do.

**Comment by spocky** [comment]
> The stock launcher looks more like something you'd see on a tablet. 
[Specs](https://ugoos.com/ugoos-am6b-plus-2021) say that this device has Android 9.0, which is different from Android Tv 9.0. If the Tv framework is not installed, there's no easy way you can get Channels that I know of.

>Is there anyway around this for me? I'd really love to see the channels but it's understandable if there's nothing you can do.
Perhaps there's a custom rom based on Android Tv ? Not sure there's anything else you can try.
