### ISSUE TITLE
Changing Android DPI to 480/640 causes the TV Row to be Unbrowsable

### ISSUE THREAD

**Issue by mo123** [spocky/miproja1#38]
Changing the Android DPI to 480/640 on GoogleTV 12 with a 3840x2160 resolution causes the TV Row to be unbrowsable then you can only press right 3-4 times then it jumps back to the first banner icon.

**Comment by spocky** [comment]
I can't manage to make GoogleTv work as expected : when I execute these commands to switch to 4k, the home screen tells me that "1920x1080 screen resolution is not compatible with GoogleTv". And everything on the UI is really big.
looking at wm size, it doesn't seem to change:
Physical size: 3840x2160
Override size: 1920x1080

**Comment by mo123** [comment]
> I can't manage to make GoogleTv work as expected : when I execute these commands to switch to 4k, the home screen tells me that "1920x1080 screen resolution is not compatible with GoogleTv". And everything on the UI is really big. looking at wm size, it doesn't seem to change: Physical size: 3840x2160 Override size: 1920x1080
> 
> Edit : got it working with 4k on my shield by using wm size 3839x2160 (which doesn't work on my CCwGTv) and then applying 640 density. With this configuration, Projectivy works as exepected.

Hi

It works correctly but only for a few hours or days and if you have multiple apps in the tv row then you can only browse to the 3rd/4th icon then it jumps back to the 1st icon.

It seems to happen when you install additional apps or open apps and go back to the launcher homescreen.
Also only happens when
Edit Category - TV Apps - **Sliding Rows Disabled**
With the default settings - Sliding Rows enabled it doesn't happen

**Comment by spocky** [comment]
Ok, I've set it up as you described. For now it works fine. I'll update this comment if I can reproduce your issue.

**Comment by mo123** [comment]
Another user reported the same problem while using a touch mouse remote.
I use a G30 airmouse.
Perhaps remotes that come with the Shield, Chromecast 4K are keyboard mode only with no mouse mode and they don't cause problems and the problem only lies with airmouse remotes that have mouse mode activated and cause extra input commands to be sent to the launcher.

**Comment by spocky** [comment]
Yes, as I wrote [here](https://xdaforums.com/t/app-android-tv-projectivy-launcher.4436549/post-89416553), the only time I saw this behavior was not related to the device resolution but to mouse-like movements.

To give you more details, Android Tv components (called "leanback") do not work well (or at all) with mouse or touchscreens. To improve compatibility, I've developped workarounds upon the stock implementation (for now only on horizontal scrolling). These are not perfect (and don't manage "grid" categories correctly) but allow minimal touchscreen usage (which also helps me debugging from my smartphone). 
This will improve in the future but as this involves hacking into the stock components to patch their behavior, it takes a lot of time for an improvement targeting a small number of users (leading it to not be top priority).

**Comment by spocky** [comment]
A changed had been made in the upcoming 4.52 to not auto select the first card or the category when it's interacted with touchscreen/air mouse and is not a "sliding row" (or a grid, but that was already the case before).
This should fix the behavior discussed here.
Don't hesitate to reopen if it's not.
