### ISSUE TITLE
[FR] Ability to remove just the app icon while keeping app names for Channels

### ISSUE THREAD

**Issue by ChaosBlades** [spocky/miproja1#40]
App icon is kind of redundant as everything in the channel will always(usually?) be from the same app and it seems some apps (Channel Connect for Plex) does not have an icon for this instead showing the android gear icon.

**Comment by spocky** [comment]
Android gear icon for apps such as Channel Connect for Plex has been fixed.
In the next release, the app icon will be on the left of the category name. Only custom and watchnext categories will still display the app icon as before.
