### ISSUE TITLE
Auto shut down with HDMI device 

### ISSUE THREAD

**Issue by Tronicgg** [spocky/miproja1#45]
I know it is an experimental feature. But it is sooo close to working on my Xiaomi projector. Xiaomi has a built in shut down menu when pressing the power off button which lets you choose from various options like restart, etc. When the auto shut down with HDMI feature is enabled it indeed "presses" the power off button but this brings me to the shut down menu, but does not shut down the projector. These devices need a second press of the power off button. So two presses. Is this something that can be done?

Thanks for the great work.

**Comment by spocky** [comment]
An option had been added for double pressing power in the next release.
