### ISSUE TITLE
Add the Hydravion app as a channel

### ISSUE THREAD

**Issue by AstudilloMarillo** [spocky/miproja1#46]
Not sure if this is something that the Hydravion app should pass itself or it's done on the Projectivy Launcher side.
I have the Hydravion app installed (which is a client to watch content from Floatplane) on my AndroidTV along with the Projectivy Launcher (of course), but unfortunately there's no way to add Hydravion as a channel (row) to the home screen. I'd love it if that were possible.

**Comment by ChaosBlades** [comment]
This should be just a standard Android TV feature that this launcher supports as I have apps that haven't been updated since this launcher came out and I can still add it as a channel. The float plane app probably just doesn't support this Android TV feature.

**Comment by AstudilloMarillo** [comment]
> This should be just a standard Android TV feature that this launcher supports as I have apps that haven't been updated since this launcher came out and I can still add it as a channel. The float plane app probably just doesn't support this Android TV feature.

Alright, I also raised it as a feature request on the Hydravion GitHub issues page. Thanks for the response.

**Comment by spocky** [comment]
To complete previous message : if hydravion shows a channel in the stock launcher, then it should also work in Projectivy (if not, then it's a bug).
If hydravion doesn't offer this option even in the stock launcher, it needs to be developed on their side before it's available on Projectivy.

As a side note, Projectivy will probably support plugins to provide cards in the future, so you won't have to solely depend on apps providing channels (instead you will have to rely on third party developers to develop plugins)

**Comment by spocky** [comment]
Closing this issue as it seems to be dependent on Hydravion. Reopen if that's a bug on Projectivy.
