### ISSUE TITLE
[Request] Suppress Network Connection Notifications

### ISSUE THREAD

**Issue by githottub** [spocky/miproja1#49]
If the additional permission to give Projectivy the ability to access and intercept notifications is enabled, does that mean it could be possible to add a feature that would suppress the routine annoying network/internet connection notifications? For example, my TV is not allowed internet access through the router, although it is sometimes plugged into the router for purposes of sideloading apps, etc. As a result, the TV is routinely displaying notifications related to connection status, no internet, etc. These obviously become very annoying. Therefore, it would be great if it could be possible for Projectivy to suppress those notifications. 

Thanks for the continued improvement of Projectivy Launcher and your consideration of this request.

**Comment by spocky** [comment]
Projectivy is informed when notifications arrive. It will add them to its own notifications panel and can dismiss them (either automatically or when the user swipes on them).
If I understand what you mean, the "no network" alerts appear as Toasts and not in the Notifications panel. This means that they are probably directly managed by the system and can't be intercepted :(

**Comment by githottub** [comment]
I understand. Thanks for the explanation. Closing request.
