### ISSUE TITLE
Add Stremio to the channels tab

### ISSUE THREAD

**Issue by luniz7** [spocky/miproja1#53]
Would like to see Stremio added to the channels tab for watch next or something like that. Syncler is there, would be nice to see Stremio join as well. Great app, thanks!

**Comment by the-badmannn** [comment]
+1

**Comment by spocky** [comment]
Is stremio showing a channel on the stock launcher ?
This is not something I can add by hand, the app has to support the TvProvider Channel api (which Syncler does), and then, it will automatically show in the Channels list.

**Comment by luniz7** [comment]
> Is stremio showing a channel on the stock launcher ? This is not something I can add by hand, the app has to support the TvProvider Channel api (which Syncler does), and then, it will automatically show in the Channels list.

I’ll check and reply back.

**Comment by luniz7** [comment]
> Is stremio showing a channel on the stock launcher ? This is not something I can add by hand, the app has to support the TvProvider Channel api (which Syncler does), and then, it will automatically show in the Channels list.

You know what? It is in the channels list. I swear it wasn’t there when I first set up the launcher though. 

Anyways I have “continue watching” channel set up. Not sure if it was something you did or something Stremio did. 

Either way, thanks for the great work!
