### ISSUE TITLE
Sony 55x85k

### ISSUE THREAD

**Issue by Shimmer2** [spocky/miproja1#55]
The shutdown of Sony TV is to sleep the system, and it cannot automatically enter the specified HDMI when waking up. I hope it can be fixed. Thank you!!

**Comment by Shimmer2** [comment]
I hope to develop a small app specifically designed to automatically open the app or switch to HDMI when the TV goes from sleep to wake-up. My name is Sony TV, I'm not sure if this can be achieved? Thank you!!

**Comment by spocky** [comment]
I added an option so that auto start also launches on resuming from standby. This should fix your issue (available on the next release).

**Comment by Shimmer2** [comment]
From hibernation to wake-up, it is possible to enter the specified HDMI, but it is not very stable, and occasionally waking up still cannot trigger the setting
