### ISSUE TITLE
[Request] Rotate wallpapers from folder or multi-select

### ISSUE THREAD

**Issue by ScottySpam** [spocky/miproja1#56]
Instead of just being able to select one wallpaper, I'd like to be able to point to a folder that contains multiple wallpapers, or have the ability to select multiple wallpapers using multi-select. Then I'd like to be able to rotate those wallpapers on some time interval (minute, hour, day), or perhaps just use a different one every time I go to the home screen.

**Comment by spocky** [comment]
This will be supported in the upcoming release ;)
