### ISSUE TITLE
Paid features not recognized 

### ISSUE THREAD

**Issue by Komputare** [spocky/miproja1#59]
I sent the payment for the paid features on your awesome app but it never unlocked.

Other than that I absolutely love your work and if I never get those working for whatever reason I'm still happy to have donated to you.

**Comment by spocky** [comment]
If you have the purchase confirmation from Google, it's probably only a communication issue with the play services. Try to purchase again  : you won't have to pay, it should tell you that "you already own this item" and refresh the purchase data.
