### ISSUE TITLE
Cropped clearlogos on Stremio posters 

### ISSUE THREAD

**Issue by izao88** [spocky/miproja1#62]
I originally posted this on the Stremio issues page. I've tested using the default launcher and it looks as if its related to Projectivy. 

I've added a video to show what's happening.. (bottom left of posters). It occurs with some other apps but it's not as noticeable. 

https://github.com/spocky/miproja1/assets/151614284/46efe57f-5784-4764-8cea-ed6264351682

**Comment by spocky** [comment]
Hi,
Thanks for the video ! On all of my apps providing "logos", the aspect ratio was always 1:1, I was not aware this could be another format.
This is fixed in upcoming 4.52.
