### ISSUE TITLE
Issue with long press menu for reducing input lag

### ISSUE THREAD

**Issue by MoMolap** [spocky/miproja1#7]
Thanks for this very convenient tool. I'm using it on batman.

I have one issue when long pressing menu to toggle input lag reduction. 
- Long press is not possible using http://mireco.hopto.org/
- Long press menu with the bluetooth remote is also assigned to specific action within batman setting therefore a sub menu appeared while toggling the input lag setting.

Alternatively,  i would like to toggle the input lag setting directly with `http://DEVICE_IP:6095/controller?action=keyevent&keycode=%s`
Would you mind sharing what keyevent/keycode could be used to toggle it ?

**Comment by spocky** [comment]
Sorry for the late reply.
This api `http://DEVICE_IP:6095/controller?action=keyevent&keycode=%s` is not managed by Projectivy : it's directly intercepted by a Xiaomi system app.
On the other hand, the "reduce input lag" feature is coded in Projectivy.
There's no way this API could communicate with Projectivy.
Projectivy might integrate an API in the future to do the kind of things you request, though.
