### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by pawel54321** [spocky/miproja1#72]
Hello,

Your project is very amazing! I use all time your Launcher. Thank you very much for your work! 

I have few qustions/issues. I have Chromecast 4.0 4k Google TV

1. I all time have disabled shortcuts and watch now. How working this tabs and how unlock? What does it mean that they are blocked? I unlock all settings projectivity Launcher: shield 5x (set boot, set "ON" settings, set notifications, set voice, TV lists read). 

2. Projectivity doesn't show option to "enabled/disabled" for Netflix  (watch continues and recommendation tab, but I see watch continue automatically working. It's weird. I have active all Netflix settings: Google account services, voice services, control voice, "your result".

I can help with issues: screenshots etc. If we need. 

P.S.
I testing github newest version and Google Play version

**Comment by spocky** [comment]
Hi,

1- Sorry I don't understand your issue.
2- Netflix is not listed in CCwGTV : this is unfortunately not dependent on Projectivy : either Google Tv or Netflix for CCwGTV don't fill the PreviewProgram database, there's noting I can do on my side :/

**Comment by spocky** [comment]
1. Projectivy doesn't create shortcuts (you can "duplicate" apps, or programs to an custom category you like, but this is not a shortcut) but it supports shortcuts made by other apps. One example on your smartphone is when you decide to pin Google weather to your launcher screen : it will then create what is called a shortcut.
More details here : https://developer.android.com/develop/ui/views/launch/shortcuts

2. It's for a reason that "Google Tv" is not called "Android Tv" : it's more closed than Android Tv. There is only one API to get PreviewPrograms that I know of. If Google is working with partners so that they implement another "private" API, there's not much I can do to get access to it unless Google decides to open it to public.

**Comment by pawel54321** [comment]
> 1. Projectivy nie tworzy skrótów (możesz „duplikować” aplikacje lub programy do niestandardowej kategorii, którą lubisz, ale nie jest to skrót), ale obsługuje skróty wykonane przez inne aplikacje. Jednym z przykładów na smartfonie jest to, że zdecydujesz się przypiąć pogodę Google do ekranu uruchamiania: następnie stworzy to, co nazywa się skrótem.
>        Więcej szczegółów tutaj : https://developer.android.com/develop/ui/views/launch/shortcuts
> 
>     2. To z jakiegoś powodu, że "Google Tv" nie jest nazywany "Android Tv": jest bardziej zamknięty niż Android Tv. Jest tylko jedno API, które znam PreviewPrograms. Jeśli Google współpracuje z partnerami, aby wdrożyć inne „prywatne” interfejs API, niewiele mogę zrobić, aby uzyskać do niego dostęp, chyba że Google zdecyduje się otworzyć go publicznie.



Thanks for the clarification.

1. You can actually create shortcuts on your phone, but I don't see such an option for applications on TV.

Will it be possible to support such actions? Create your own shortcuts for: movies (videos) OR special actions, for example restarting the device. So that the user can create them? This would be a great option. But does this go beyond your Launcher? Or do you know such applications?

<><><>Mostly a personal question<><><>

I also tried to create various *.apk applications myself (I don't know Java and the Android API that well) from examples (Landspace):

https://developer.android.com/training/tv/discovery/recommendations-channel?hl=pl
https://developer.android.com/training/tv/discovery/recommendations-row?hl=pl#service
https://developer.android.com/codelabs/tv-channels-programs?hl=en#0
https://github.com/googlearchive/androidtv-leanback

BUT it doesn't show recommendations on the desktop, I don't know why. Unless you know from your extensive experience. "how to go beyond applications with code"? What is the maximum number of channels the Launcher can handle for applications if I managed to do this for multiple categories:
1. Popular Comedies
2. Popular Adventure
(...)
and connect it with, for example, the API https://www.themoviedb.org/?language=pl based on selected streaming services
and then probably the path to opening a streaming service

If you could suggest something, I would be very grateful. I appreciate your work and development on the Launcher :)

**Comment by pawel54321** [comment]
> 1. Projectivy doesn't create shortcuts (you can "duplicate" apps, or programs to an custom category you like, but this is not a shortcut) but it supports shortcuts made by other apps. One example on your smartphone is when you decide to pin Google weather to your launcher screen : it will then create what is called a shortcut.
>        More details here : https://developer.android.com/develop/ui/views/launch/shortcuts
> 
>     2. It's for a reason that "Google Tv" is not called "Android Tv" : it's more closed than Android Tv. There is only one API to get PreviewPrograms that I know of. If Google is working with partners so that they implement another "private" API, there's not much I can do to get access to it unless Google decides to open it to public.



Thanks for the clarification.

1. You can actually create shortcuts on your phone, but I don't see such an option for applications on Google TV.

Will it be possible to support such actions? Create your own shortcuts for: movies (videos) OR special actions, for example restarting the device. So that the user can create them? This would be a great option. But does this go beyond your Launcher? Or do you know such applications?

<><><>Mostly a personal question<><><>

I also tried to create various *.apk applications myself (I don't know Java and the Android API that well) from examples (Landspace):

https://developer.android.com/training/tv/discovery/recommendations-channel?hl=pl
https://developer.android.com/training/tv/discovery/recommendations-row?hl=pl#service
https://developer.android.com/codelabs/tv-channels-programs?hl=en#0
https://github.com/googlearchive/androidtv-leanback

BUT it doesn't show recommendations on the desktop, I don't know why. Unless you know from your extensive experience. "how to go beyond applications with code"? What is the maximum number of channels the Launcher can handle for applications if I managed to do this for multiple categories:
1. Popular Comedies
2. Popular Adventure
(...)
and connect it with, for example, the API https://www.themoviedb.org/?language=pl based on selected streaming services
and then probably the path to opening a streaming service

If you could suggest something, I would be very grateful. I appreciate your work and development on the Launcher :)
