### ISSUE TITLE
Picture homescreen resolution

### ISSUE THREAD

**Issue by Brinet16** [spocky/miproja1#73]
Hi

Thanks for all your hard work and another great update.

I've updated to 4.51 and I've noticed one thing regarding background images on the main homescreen. 

Ive had my menu/homescreen set to 4k (3840x2160) and in the previous version custom images were showing in 4k.

But I've noticed that the images now, whether selected individually or in a selected folder don't quite appear to be 4k resolution.

All the images I use are taken or cropped to that same 4k resolution, and if I view the pictures in a image viewer they look fine.

Is the new update slightly reducing the resolution of background images?

Thanks

Brian

**Comment by spocky** [comment]
Hi, thanks for your feedback.
You're totally right, this will get fixed in 4.52
