### ISSUE TITLE
map esc to back button and Enter to Enter

### ISSUE THREAD

**Issue by lpuglia** [spocky/miproja1#74]
I'm using my google tv with an air-mouse remote (it's a game changer compared to the default IR remote), the problem is that some buttons are not mapped to very same buttons of the IR remote.

For example, the back button of the air-mouse is mapped to the ESC key code:
https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_ESCAPE

instead of the BACK key code:
https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_BACK

This prevents me from going back while I'm in the settings menu of Projectivity Launcher.

Another annoying mapping is the central OK button which on the air-mouse is mapped to  https://developer.android.com/reference/android/view/KeyEvent#NUMPAD_ENTER

instead of 
https://developer.android.com/reference/android/view/KeyEvent#DPAD_CENTER 

this prevents me from pressing enter when I'm in this part of the Projectivity Launcher:
![image](https://github.com/spocky/miproja1/assets/2184440/ff4d7a32-eb11-4d9c-8630-0759ff775391)

i can't sort the channels, nor i can access the settings of the highlighted app.

It would be great if these additional keys were supported!

**Comment by spocky** [comment]
While this can't be done globally, the requests mentionned above (and a few more) should be fixed in 4.52.
Don't hesitate to reopen if something is missing.
