### ISSUE TITLE
Request - OLED wallpapers 

### ISSUE THREAD

**Issue by x7p7p** [spocky/miproja1#75]
Hello can we get r/Amoledbackgrounds on the app for black wallpapers 🙏

**Comment by spocky** [comment]
Hi,
On 4.5+, you can specify the subreddit you wish with the "custom" option.
I won't add it to the predefined list as it seems there are almost only portrait mode pictures, which don't really play well on television.

**Comment by KarthiSurfer** [comment]
@spocky , which format we need to use in the custom subreddit field, is it r/subreddit or only subreddit
