### ISSUE TITLE
Back button shouldn't go to previous app

### ISSUE THREAD

**Issue by kindall** [spocky/miproja1#76]
No other launcher I've used allows the Back button to leave the launcher and return to the last-used app.  This behavior confuses the wife.  (And me sometimes.)

Once the Back button goes to the beginning of a category, it should be blocked from leaving Projectivy, or if the behavior is desired for some reason, there should be a setting to turn it off. Maybe a third option to go directly to ambient mode like in the Google TV home screen? Although you already have an option for double-back to do that.

**Comment by spocky** [comment]
Hi,

Projectivy is an Android Tv Launcher. However, Android Tv doesn't really allow to change the launcher as long as the stock one is installed. You either need to disable the stock launcher (then the system will let you choose another installed launcher, and back will work as intended) or use workarounds such as Projectivy's accessibility service and use the "Oerride stock launcher" option in Projectivy settings (that will intercept "home" buttons and calls to the stock launcher, and once again, in that case, back will work as intended).

Doing what you request (intercepting back without the user explicitely enabling the "override stock launcher" + accessibility setting option) will result in a half backed situation where back won't let you quit but home will still revert to the stock launcher.
I hope that makes sense.
