### ISSUE TITLE
4.52 crash

### ISSUE THREAD

**Issue by dctrbnsttr** [spocky/miproja1#84]
Installed 4.52 over version 4.51 on Nvidia Shield TV Pro. Projectivy crashes immediately after splash ecreen when launched.

**Comment by xiringuelu** [comment]
Same issue here. I had to clear app data to fix it.

**Comment by dctrbnsttr** [comment]
Could you then restore settings saved with version 4.51? It would be painful to have to set it all up again.

**Comment by xiringuelu** [comment]
> Could you then restore settings saved with version 4.51? It would be painful to have to set it all up again.

Yes, that's exactly what I did.

**Comment by dctrbnsttr** [comment]
Thanks for the info..... I will give it a go

**Comment by dctrbnsttr** [comment]
Deleting cache AND data after installing 4.52 and then importing previous settings gets things up and running. You do need to have the original launcher or another launcher available at first to be able to do this.

**Comment by spocky** [comment]
Those with crash on startup, could your please tell me what was your wallpaper please?

**Comment by xiringuelu** [comment]
Mine was a custom folder with videos.

**Comment by dctrbnsttr** [comment]
Mine was a custom picture from a folder. Previously, I was never able to select a custom folder.... it hadn't worked until the 4.52 version.

**Comment by spocky** [comment]
Fixed. 4.53 coming in the next few hours.
