### ISSUE TITLE
There is no download link for 4.52

### ISSUE THREAD

**Issue by truth7seeker** [spocky/miproja1#87]
I am trying to download this and all I see is your zip files for source codes, no release?

**Comment by steve51184** [comment]
Hmm yeah it's gone.. I wonder if the dev removed it for some big bug or something.. works fine for me though lol

**Comment by truth7seeker** [comment]
Not sure bud, I did see someone mentioned it had removed Thier custom icons, so maybe that is why?

**Comment by steve51184** [comment]
Possibly but I didn't find that option yet anyway 😕

**Comment by spocky** [comment]
https://github.com/spocky/miproja1/releases/tag/4.53
