### ISSUE TITLE
Can't buy the app on Nvidia Shield?

### ISSUE THREAD

**Issue by steve51184** [spocky/miproja1#90]
Says "this version isn't configured for billing" when trying to buy via the app..

I'm on v4.52

![IMG_20240407_021638](https://github.com/spocky/miproja1/assets/12534098/55ad10ff-1e62-4cb0-aa0e-347b28c9e8b0)

**Comment by spocky** [comment]
The Play store doesn't know this version yet. You need to buy from a version available on the play store and then update to this version if you wish.
Or just wait until (hopefully) tomorrow, so that the play store is updated with the latest release.

**Comment by steve51184** [comment]
Ok Ty
