### ISSUE TITLE
UI Opacity

### ISSUE THREAD

**Issue by AitoZ** [spocky/miproja1#92]
I think I've found a bug in the latest version, as soon as I raise the setting **UI Opacity** to **100%** both settings under **Launcher Idle Mode** are grayed out and I can't change them anymore. Before I raised it to **100%** it was working properly, I've tested it on two devices with different Android versions that's the reason why I think it could be a bug in the latest version.

**Comment by spocky** [comment]
Thanks for your feedback. 
This is not a bug : some users didn't understand how to disable the "launcher idle mode". Settings UI opacity to 100% will do exactly this (which makes sense : the only goal of "launcher idle mode" is to fade the icons, if there's no fade, it's essentially the same as if it was disabled)

**Comment by AitoZ** [comment]
I know what it does, how do you turn it on again? Isn't that option missing or am I missing something?
